name: Check that every PR meets requirement
on:
  pull_request:
    branches: [master]
jobs:
  pr-incoming-head-must-have-success-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: ./.github/workflows/scripts/pr-requirements/pr-incoming-head-must-have-success-run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-incoming-convetional-commits-lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "GITHUB_SHA is ${{ github.sha }}, github.event.pull_request.head.sha is ${{ github.event.pull_request.head.sha }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: npm install
        working-directory: ./.github/workflows/scripts/pr-requirements
      - run: ./pr-incoming-convetional-commits-lint.sh
        working-directory: ./.github/workflows/scripts/pr-requirements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-need-rebase-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: ./.github/workflows/scripts/pr-requirements/pr-need-rebase-label.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}